name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  actions: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: 🐳 Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: 🚀 Deploy to production
    runs-on: [self-hosted]
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Deploy container
        run: |
          echo "Pull latest image"
          docker pull mouctarlawan/portfolio-mac:production

          echo "Stop old container"
          docker stop portfolio-mac || true
          docker rm portfolio-mac || true

          echo "Run new container"
          docker run -d \
            --name portfolio-mac \
            --restart always \
            -p 3001:80 \
            mouctarlawan/portfolio-mac:production

          echo "Cleanup unused images"
          docker image prune -f